# Generated by Django 4.2.3 on 2023-07-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comtact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pho', models.CharField(max_length=50)),
                ('decs', models.CharField(max_length=600)),
                ('date', models.DateField()),
            ],
        ),
    ]
